SELECT
    DISTINCT A.CAR_ID   
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A JOIN CAR_RENTAL_COMPANY_CAR AS B
    ON A.CAR_ID = B.CAR_ID
WHERE
    B.CAR_TYPE = "세단"
    AND DATE_FORMAT(A.START_DATE, "%m") = "10"
ORDER BY
    A.CAR_ID DESC
;
