SELECT 
    MEMBER_ID, 
    MEMBER_NAME, 
    GENDER, 
    substr(DATE_OF_BIRTH, 1, 10) AS DATE_OF_BIRTH
FROM 
    MEMBER_PROFILE 
WHERE 
    substr(DATE_OF_BIRTH, 7, 1) = '3' 
    AND GENDER = 'W' 
    AND TLNO IS NOT NULL
ORDER BY 
    MEMBER_ID ASC