SELECT
    B.PRODUCT_ID,
    B.PRODUCT_NAME,
    SUM(A.AMOUNT * B.PRICE) AS TOTAL_SALES
FROM
    FOOD_ORDER AS A LEFT JOIN FOOD_PRODUCT AS B
    ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE
    SUBSTR(A.PRODUCE_DATE, 1, 7) = '2022-05'
    AND B.PRODUCT_ID IS NOT NULL
GROUP BY 
    B.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    B.PRODUCT_ID
;
